<?php

namespace Database\Seeders;

use App\Models\BlogPost;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BlogSeeder extends Seeder
{
    public function run(): void
    {
        $author = User::where('email', 'instructor@lmsportal.com')->first()
            ?? User::where('email', 'admin@lmsportal.com')->first();

        $posts = [
            [
                'title' => '10 Study Habits of Highly Successful Online Learners',
                'category' => 'Learning Tips',
                'excerpt' => 'Discover the proven routines and techniques that separate students who finish what they start from those who stall halfway through.',
                'content' => "Online learning gives you incredible freedom — and that freedom is exactly why so many learners struggle. Without a classroom, a fixed schedule, or a teacher watching over your shoulder, success depends entirely on the systems you build for yourself.\n\nAfter analyzing the behavior of thousands of successful students on our platform, we found ten habits that show up again and again.\n\n## 1. They schedule learning like a meeting\n\nSuccessful learners don't wait to \"find time\" — they block time. Whether it's 6:30 AM before work or 9 PM after the kids are in bed, top students treat their study block as non-negotiable.\n\n## 2. They learn in small, daily doses\n\nThirty minutes every day beats four hours once a week. Spaced repetition is one of the most robust findings in learning science: short, frequent sessions move knowledge into long-term memory far more effectively than cramming.\n\n## 3. They take notes by hand\n\nEven when watching video lessons, writing key ideas down forces your brain to process and summarize instead of passively consuming.\n\n## 4. They apply within 24 hours\n\nKnowledge you don't use fades fast. The best learners complete the exercise, build the mini-project, or write the code immediately after finishing a lesson.\n\n## 5. They embrace being a beginner\n\nFeeling confused is not a sign of failure — it's the feeling of learning. Students who accept discomfort push through plateaus that stop others.\n\n## 6. They use discussion sections\n\nAsking questions and answering others is one of the fastest ways to expose gaps in your own understanding.\n\n## 7. They track progress visually\n\nWatching a course progress bar climb from 40% to 60% releases real motivation. Our data shows students who complete at least one module per week are five times more likely to finish a course.\n\n## 8. They teach what they learn\n\nExplaining a concept out loud — to a friend, a rubber duck, or a study group — is the famous Feynman technique, and it works.\n\n## 9. They protect deep-focus time\n\nPhone in another room. Notifications off. One tab. Deep focus compounds.\n\n## 10. They finish courses before starting new ones\n\nCourse-hopping feels productive but leaves a trail of 15%-complete enrollments. Finish first, then branch out.\n\nStart with just two or three of these habits this week. Small systems beat big intentions.",
            ],
            [
                'title' => 'Web Development in 2026: Skills That Actually Get You Hired',
                'category' => 'Career Advice',
                'excerpt' => 'The web dev landscape changes fast. Here is an honest breakdown of the technologies and fundamentals employers are really asking for this year.',
                'content' => "Every year brings a fresh wave of frameworks, tools, and hot takes about the future of web development. So which skills actually matter in 2026? We reviewed hundreds of junior developer job postings and spoke with engineering managers to find out.\n\n## The fundamentals still dominate\n\nAcross every job posting analysis, the same core trio appears again and again:\n\n- **HTML, CSS, and JavaScript** — still the non-negotiable foundation\n- **Git & collaborative workflows** — pull requests, code review, branching strategies\n- **HTTP, APIs, and how the web actually works** — surprisingly rare among juniors, instantly noticed by seniors\n\nFrameworks change; fundamentals compound. A developer who deeply understands the platform can pick up any framework in weeks.\n\n## What employers ask for right now\n\n**1. TypeScript** has effectively become the default in professional front-end work. Job postings mentioning TypeScript have tripled in three years.\n\n**2. React remains the most requested library**, followed at a distance by Vue and Svelte. But interviewers increasingly test underlying concepts — rendering, state, data flow — rather than syntax.\n\n**3. Node.js or PHP on the backend** still power a massive share of the web. Laravel in particular has had a renaissance thanks to its developer experience.\n\n**4. SQL never went away.** Every serious application needs someone who can write a correct JOIN and read a query plan.\n\n**5. AI-assisted development** is now an expected skill — knowing how to prompt, evaluate, and verify AI-generated code separates efficient developers from dangerous ones.\n\n## What matters more than any technology\n\nHiring managers consistently tell us the same thing: they hire for **problem-solving ability, communication, and proof of shipped work**. A portfolio with three polished projects — deployed, documented, with tests — beats a certificate wall every single time.\n\n## Your realistic roadmap\n\n1. Months 1–3: HTML, CSS, modern JavaScript\n2. Months 4–5: Git, TypeScript, React basics\n3. Months 6–7: Backend (Node or PHP/Laravel) + SQL + authentication\n4. Months 8–9: Build and deploy three real portfolio projects\n5. Month 10+: Contribute to open source, practice interviews, apply widely\n\nConsistency wins. One focused hour a day will get you further than weekend heroics ever will.",
            ],
            [
                'title' => 'How to Choose the Right Programming Language to Learn First',
                'category' => 'Learning Tips',
                'excerpt' => 'Python? JavaScript? PHP? The honest answer depends on what you want to build. This guide matches languages to goals so you can stop second-guessing.',
                'content' => "\"Which language should I learn first?\" is the most common question in every programming community — and it causes more paralysis than almost anything else for beginners.\n\nHere's the truth: **the first language matters far less than starting**. Concepts like variables, loops, conditionals, and functions transfer between virtually all mainstream languages. That said, matching your first language to your goal makes everything more motivating.\n\n## Match the language to what you want to build\n\n**\"I want to build websites.\"** → JavaScript. It's the only language browsers run natively, so your work is instantly visible.\n\n**\"I want to work with data, AI, or automation.\"** → Python. Its readable syntax was practically designed for beginners, and its ecosystem (pandas, PyTorch, scikit-learn) is unmatched.\n\n**\"I want to build web applications end-to-end.\"** → PHP with Laravel, or JavaScript with Node. Both let one language carry you from database to browser.\n\n**\"I want to build mobile apps.\"** → Start with JavaScript (React Native) or learn Dart/Flutter.\n\n**\"I just want to understand programming.\"** → Python. Full stop.\n\n## The criteria that actually matter\n\n1. **Fast feedback loop** — seeing results quickly keeps motivation alive\n2. **Beginner-friendly community** — your errors should be Googleable\n3. **Job market depth** — eventually you may want to get paid\n4. **Room to grow** — the language shouldn't box you into toys\n\nBy these measures, JavaScript and Python are the strongest first choices for most people. But don't overthink it.\n\n## The anti-advice section\n\n- Don't learn C first because someone said it builds character\n- Don't chase the \"highest paying language\" lists\n- Don't switch languages the moment something gets hard — confusion is where learning happens\n\nPick one based on your goal, commit to 90 days, build small things constantly. The second language is dramatically easier than the first — getting to competent in language #1 is the whole battle.",
            ],
            [
                'title' => 'From Zero to Certified: Maria\'s Journey into Data Science',
                'category' => 'Student Stories',
                'excerpt' => 'A former retail manager with no technical background shares how she went from spreadsheet basics to landing her first analyst role in eleven months.',
                'content' => "Maria Gonzalez spent eight years managing a retail store. Today she works as a junior data analyst at a logistics company. Her path between those two points took eleven months of disciplined evening study. We sat down with her to hear how she did it.\n\n**What made you decide to switch careers?**\n\nI was drowning in spreadsheets at work and I realized I enjoyed finding patterns in our sales numbers more than anything else in my job. A friend showed me a dashboard she'd built and I remember thinking: I want to make things like that.\n\n**How did you structure your learning?**\n\nNinety minutes every night after my son went to bed, no exceptions. I started with spreadsheet fundamentals, then SQL, then Python. Honestly, SQL was the unlock — suddenly I could answer my own questions instead of waiting for IT.\n\n**What was the hardest part?**\n\nMonth three or four. The honeymoon phase ends and statistics starts feeling like math class again. What saved me was working with real, messy data — cleaning a genuinely ugly sales dataset taught me more than any perfect textbook example.\n\n**How did you land the job?**\n\nI rebuilt my store's entire inventory reporting as a portfolio project. In interviews, nobody asked about my degree — they asked me to walk through that project. Being able to say \"this saved my company six hours a week\" was worth more than any certificate alone.\n\n**What would you tell someone standing where you stood?**\n\nYou don't need to be a genius. You need consistency and one project you can talk about with pride. Start before you feel ready — I never felt ready.\n\nMaria's story mirrors a pattern we see constantly: structured learning, real projects, and visible progress add up to career changes that feel impossible at the start.",
            ],
            [
                'title' => 'The Science of Retention: Why You Forget 70% of What You Learn',
                'category' => 'Learning Tips',
                'excerpt' => 'The forgetting curve is real — but beatable. Here is how spaced repetition, active recall, and project-based learning lock knowledge in place.',
                'content' => "In the 1880s, psychologist Hermann Ebbinghaus charted something uncomfortable about the human mind: within days of learning new information, we lose most of it. Modern research puts the numbers bluntly — without reinforcement, up to 70% of new material vanishes within 24 hours.\n\nIf you've ever finished a course feeling sharp, only to draw a blank a month later, you've met the forgetting curve personally. The good news: a century of cognitive science gives us reliable weapons against it.\n\n## Weapon #1: Active recall\n\nRe-reading notes feels productive but does almost nothing. Actively *retrieving* information — answering questions from memory, explaining concepts aloud, solving problems cold — strengthens memory each time you do it.\n\nPractical version: after each video lesson, close everything and write down everything you remember. Then check what you missed. Five minutes, transformative effect.\n\n## Weapon #2: Spaced repetition\n\nMemory strengthens most when review happens *just as* you're about to forget. The optimal schedule looks roughly like this:\n\n- Review 1: one day after learning\n- Review 2: three days later\n- Review 3: one week later\n- Review 4: two weeks later\n\nOur quiz system is built around exactly this principle — retaking tests after a gap isn't cheating your progress, it *is* progress.\n\n## Weapon #3: Interleaving\n\nInstead of drilling one topic for hours (blocked practice), mix related topics. If you're learning CSS, alternate between layout, typography, and color exercises rather than doing thirty layout problems in a row. It feels harder — and that difficulty is precisely what builds durable skill.\n\n## Weapon #4: Project-based anchoring\n\nFacts attached to experiences stick; facts floating free don't. When you build a real project, every concept you used gains a location, a context, and a story. This is why portfolio-based learning consistently outperforms lecture-based learning for retention.\n\n## The takeaway\n\nForgetting isn't failure — it's the default. Learning is what happens when you deliberately fight back. Build retrieval, spacing, mixing, and making into your routine, and the 70% loss becomes a 20% loss. Over months, that difference compounds into mastery.",
            ],
            [
                'title' => 'Design Thinking Explained: Solve Problems Like a Product Designer',
                'category' => 'Design',
                'excerpt' => 'Empathize, define, ideate, prototype, test. The five-stage design thinking process turns messy problems into elegant solutions — here\'s how to use it.',
                'content' => "Great products rarely come from great first ideas. They come from a disciplined process of understanding people, exploring many possibilities, and testing assumptions cheaply before betting big. That process has a name: design thinking.\n\n## Stage 1: Empathize\n\nEverything starts with real users — not assumptions about users. Watch people struggle with the problem you want to solve. Interview them. Ask \"why\" until things get uncomfortable. The goal isn't validation; it's discovery of what people actually do versus what they claim they do.\n\n## Stage 2: Define\n\nSynthesize what you learned into a clear problem statement: *\"[User] needs [need] because [insight].\"* Teams that skip this stage solve symptoms. A well-defined problem is half-solved.\n\n## Stage 3: Ideate\n\nNow generate options — lots of them. Quantity over quality at this stage. Techniques that work:\n\n- **Crazy 8s**: eight sketches in eight minutes\n- **Worst possible idea**: deliberately terrible solutions often reveal hidden constraints\n- **SCAMPER**: substitute, combine, adapt, modify, put to other uses, eliminate, reverse\n\n## Stage 4: Prototype\n\nBuild the cheapest possible version of your best ideas. Paper sketches. Clickable wireframes in Figma. Landing pages. The rule: if you're not embarrassed by how rough it is, you spent too long on it.\n\n## Stage 5: Test\n\nPut prototypes in front of real people. Watch where they hesitate. Say less; observe more. Testing isn't about proving your design right — it's about discovering where reality disagrees with your assumptions.\n\nThen loop. Design thinking is not linear; it's a cycle of increasing refinement.\n\n## Why developers should care\n\nYou don't need the job title to benefit from the method. Any engineer who can empathize with users, frame problems sharply, and test cheaply ships better software. The five stages fit on a sticky note — but practiced consistently, they change how you think about building anything.",
            ],
        ];

        foreach ($posts as $i => $data) {
            BlogPost::updateOrCreate(
                ['slug' => Str::slug($data['title'])],
                $data + [
                    'author_id' => $author?->id,
                    'published_at' => now()->subDays((count($posts) - $i) * 7),
                    'views' => rand(400, 5200),
                ]
            );
        }
    }
}
